name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install 
    - run: npm install -g firebase-tools
    - run: npm run build
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - run: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
